framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'projet.ykcr@gmail.com'
        headers:
            from: 'Yannick <projet.ykcr@gmail.com>'
            

